genconfig:
    talosctl gen config --with-secrets secrets.yaml controlplane-rizexor-prod1 https://140.245.250.113:6443 \
      --kubernetes-version 1.35.0 --talos-version 1.12.0 \
      --config-patch @patches/cert-approver.yaml --config-patch @patches/hostdns.yaml \
      --config-patch @patches/oracle-ntp.yaml --config-patch @patches/topolvm.yaml \
      --config-patch @patches/scheduling.yaml --config-patch @patches/cilium.yaml --config-patch @patches/cert-sans.yaml \
      --force
