apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  # Victoria Metrics secrets
  - prod-secrets/victoria-metrics-alertmanager.yaml
  - prod-secrets/victoria-metrics-discord-webhook.yaml
