apiVersion: v1
stringData:
    token: ENC[AES256_GCM,data:jyv5LI9/TTqwo8cOtIpPaxSyafMWT22NEUCm234GAha9bEV6kp5ODHva6YkODq11sMCCYIYiAGLYO+SZ+xZkAJdsp8nhBnOeL2q5mBOqjvbIqpxrG/1p16A4dGF/uOiFoPZxwGceF0/+PafQXP9nIyL0E6x3BCAF8Q==,iv:EWfY5Hp3m94NEaGvCyhMRQ76AgUl32SzwwtFqnrL8oc=,tag:K8SKiu12Ck7zn/xwubLzBg==,type:str]
    info: ENC[AES256_GCM,data:Y66FevWn5UptxrOAqF3wcgsuvcPvMHAAZFwKTnOnysxfV0osi5LQgrEFFkidaIODcFH6WT5HIqFyIi3UHAzLZZ71peZjNIQSNa+J8b2M3EIUhNGyi2A2Fjqq9oLxumjKTB3wiX4soutA/b4UtulkU1l1DqMEhQ4J3g==,iv:mC/qYtV+JjLnQx71rgOkySTdxx7OOWriVAXuYhcNEF8=,tag:e0SjzdExpEBZTlTAB0VEtw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: discord-webhook
    namespace: observability
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUzJVKy95TzEySmg3dUtP
            ZllPQ21sRTd3bW9HZGd0SURjUkU5Sk1GRHo4CkxDY1hVSW04TENnZHRrWVhENXAw
            enNGSG5hTkYxSXdqT0tNS01MUWJKNmsKLS0tIDhqMlpjbTlmczgzcHpIWFQ2cWZm
            VXdPNnZ4WWtYeWNUOGJ0WXJZbEVlcUUK0mdeHD+DYZkj55TJvDvDFFTJyTLbl0XK
            1kAvxj339V7v5Wrs1oBhmnIo5dlVgsM+OH9CbMTe3UuTsDzzaLRbOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T08:24:03Z"
    mac: ENC[AES256_GCM,data:X6YGJMP27dFXAUEFauI0uDbF469tslzzgN1z5dIiHKcGX4jU/JgTsnFJWzO7/0T8h+NQx95EzEa84Q38wZzbF0EDJcnnID588Df65vAZvsLAKiNGl+6nweDKsWxTVNRoZELHla68Y0cKCZ+a19RKBhyX4yP1WIfhxdVKlvqm408=,iv:df55hYldMzXyDlS7Paj7yRRAAdrr2K6v17Tz4L2fDlQ=,tag:caq2svM3OvUfxSY4U6xevg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
