# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: observability
spec:
  interval: 30m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-k8s-stack
    namespace: observability
  maxHistory: 3
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  releaseName: stack
  values:
    fullnameOverride: stack

    external:
      grafana:
        host: "grafana.${DOMAIN}"

    defaultDashboards:
      defaultTimezone: ist
      grafanaOperator:
        enabled: true

    defaultDatasources:
      grafanaOperator:
        enabled: true

    grafana:
      enabled: false
      forceDeployDatasource: true

    vmsingle:
      enabled: true
      spec:
        extraArgs:
          opentelemetry.usePrometheusNaming: "true"

        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
          seccompProfile: { type: RuntimeDefault }

    vmagent:
      spec:
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 500Mi

    kube-state-metrics:
      kube-state-metrics:
        # For kube-prometheus-stacks that are already installed and configured with
        # custom collectors, commenting out the collectors and extraArgs below will
        # retain any existing kube-state-metrics configuration.
        collectors: [ ]
        extraArgs:
          - --custom-resource-state-only=true
        rbac:
          extraRules:
            - apiGroups:
                - source.toolkit.fluxcd.io
                - kustomize.toolkit.fluxcd.io
                - helm.toolkit.fluxcd.io
                - notification.toolkit.fluxcd.io
                - image.toolkit.fluxcd.io
              resources:
                - gitrepositories
                - buckets
                - helmrepositories
                - helmcharts
                - ocirepositories
                - kustomizations
                - helmreleases
                - alerts
                - providers
                - receivers
                - imagerepositories
                - imagepolicies
                - imageupdateautomations
              verbs: [ "list", "watch" ]
        customResourceState:
          enabled: true
          config:
            spec:
              resources:
                - groupVersionKind:
                    group: kustomize.toolkit.fluxcd.io
                    version: v1
                    kind: Kustomization
                  metricNamePrefix: gotk
                  metrics:
                    - name: "resource_info"
                      help: "The current state of a Flux Kustomization resource."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            name: [ metadata, name ]
                      labelsFromPath:
                        exported_namespace: [ metadata, namespace ]
                        ready: [ status, conditions, "[type=Ready]", status ]
                        suspended: [ spec, suspend ]
                        revision: [ status, lastAppliedRevision ]
                        source_name: [ spec, sourceRef, name ]
                - groupVersionKind:
                    group: helm.toolkit.fluxcd.io
                    version: v2
                    kind: HelmRelease
                  metricNamePrefix: gotk
                  metrics:
                    - name: "resource_info"
                      help: "The current state of a Flux HelmRelease resource."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            name: [ metadata, name ]
                      labelsFromPath:
                        exported_namespace: [ metadata, namespace ]
                        ready: [ status, conditions, "[type=Ready]", status ]
                        suspended: [ spec, suspend ]
                        revision: [ status, history, "0", chartVersion ]
                        chart_name: [ status, history, "0", chartName ]
                        chart_app_version: [ status, history, "0", appVersion ]
                        chart_ref_name: [ spec, chartRef, name ]
                        chart_source_name: [ spec, chart, spec, sourceRef, name ]
                - groupVersionKind:
                    group: source.toolkit.fluxcd.io
                    version: v1
                    kind: GitRepository
                  metricNamePrefix: gotk
                  metrics:
                    - name: "resource_info"
                      help: "The current state of a Flux GitRepository resource."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            name: [ metadata, name ]
                      labelsFromPath:
                        exported_namespace: [ metadata, namespace ]
                        ready: [ status, conditions, "[type=Ready]", status ]
                        suspended: [ spec, suspend ]
                        revision: [ status, artifact, revision ]
                        url: [ spec, url ]
                - groupVersionKind:
                    group: source.toolkit.fluxcd.io
                    version: v1
                    kind: Bucket
                  metricNamePrefix: gotk
                  metrics:
                    - name: "resource_info"
                      help: "The current state of a Flux Bucket resource."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            name: [ metadata, name ]
                      labelsFromPath:
                        exported_namespace: [ metadata, namespace ]
                        ready: [ status, conditions, "[type=Ready]", status ]
                        suspended: [ spec, suspend ]
                        revision: [ status, artifact, revision ]
                        endpoint: [ spec, endpoint ]
                        bucket_name: [ spec, bucketName ]
                - groupVersionKind:
                    group: source.toolkit.fluxcd.io
                    version: v1
                    kind: HelmRepository
                  metricNamePrefix: gotk
                  metrics:
                    - name: "resource_info"
                      help: "The current state of a Flux HelmRepository resource."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            name: [ metadata, name ]
                      labelsFromPath:
                        exported_namespace: [ metadata, namespace ]
                        ready: [ status, conditions, "[type=Ready]", status ]
                        suspended: [ spec, suspend ]
                        revision: [ status, artifact, revision ]
                        url: [ spec, url ]
                - groupVersionKind:
                    group: source.toolkit.fluxcd.io
                    version: v1
                    kind: HelmChart
                  metricNamePrefix: gotk
                  metrics:
                    - name: "resource_info"
                      help: "The current state of a Flux HelmChart resource."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            name: [ metadata, name ]
                      labelsFromPath:
                        exported_namespace: [ metadata, namespace ]
                        ready: [ status, conditions, "[type=Ready]", status ]
                        suspended: [ spec, suspend ]
                        revision: [ status, artifact, revision ]
                        chart_name: [ spec, chart ]
                        chart_version: [ spec, version ]
                - groupVersionKind:
                    group: source.toolkit.fluxcd.io
                    version: v1
                    kind: OCIRepository
                  metricNamePrefix: gotk
                  metrics:
                    - name: "resource_info"
                      help: "The current state of a Flux OCIRepository resource."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            name: [ metadata, name ]
                      labelsFromPath:
                        exported_namespace: [ metadata, namespace ]
                        ready: [ status, conditions, "[type=Ready]", status ]
                        suspended: [ spec, suspend ]
                        revision: [ status, artifact, revision ]
                        url: [ spec, url ]
                - groupVersionKind:
                    group: notification.toolkit.fluxcd.io
                    version: v1beta3
                    kind: Alert
                  metricNamePrefix: gotk
                  metrics:
                    - name: "resource_info"
                      help: "The current state of a Flux Alert resource."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            name: [ metadata, name ]
                      labelsFromPath:
                        exported_namespace: [ metadata, namespace ]
                        suspended: [ spec, suspend ]
                - groupVersionKind:
                    group: notification.toolkit.fluxcd.io
                    version: v1beta3
                    kind: Provider
                  metricNamePrefix: gotk
                  metrics:
                    - name: "resource_info"
                      help: "The current state of a Flux Provider resource."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            name: [ metadata, name ]
                      labelsFromPath:
                        exported_namespace: [ metadata, namespace ]
                        suspended: [ spec, suspend ]
                - groupVersionKind:
                    group: notification.toolkit.fluxcd.io
                    version: v1
                    kind: Receiver
                  metricNamePrefix: gotk
                  metrics:
                    - name: "resource_info"
                      help: "The current state of a Flux Receiver resource."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            name: [ metadata, name ]
                      labelsFromPath:
                        exported_namespace: [ metadata, namespace ]
                        ready: [ status, conditions, "[type=Ready]", status ]
                        suspended: [ spec, suspend ]
                        webhook_path: [ status, webhookPath ]
                - groupVersionKind:
                    group: image.toolkit.fluxcd.io
                    version: v1
                    kind: ImageRepository
                  metricNamePrefix: gotk
                  metrics:
                    - name: "resource_info"
                      help: "The current state of a Flux ImageRepository resource."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            name: [ metadata, name ]
                      labelsFromPath:
                        exported_namespace: [ metadata, namespace ]
                        ready: [ status, conditions, "[type=Ready]", status ]
                        suspended: [ spec, suspend ]
                        image: [ spec, image ]
                - groupVersionKind:
                    group: image.toolkit.fluxcd.io
                    version: v1
                    kind: ImagePolicy
                  metricNamePrefix: gotk
                  metrics:
                    - name: "resource_info"
                      help: "The current state of a Flux ImagePolicy resource."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            name: [ metadata, name ]
                      labelsFromPath:
                        exported_namespace: [ metadata, namespace ]
                        ready: [ status, conditions, "[type=Ready]", status ]
                        suspended: [ spec, suspend ]
                        source_name: [ spec, imageRepositoryRef, name ]
                - groupVersionKind:
                    group: image.toolkit.fluxcd.io
                    version: v1
                    kind: ImageUpdateAutomation
                  metricNamePrefix: gotk
                  metrics:
                    - name: "resource_info"
                      help: "The current state of a Flux ImageUpdateAutomation resource."
                      each:
                        type: Info
                        info:
                          labelsFromPath:
                            name: [ metadata, name ]
                      labelsFromPath:
                        exported_namespace: [ metadata, namespace ]
                        ready: [ status, conditions, "[type=Ready]", status ]
                        suspended: [ spec, suspend ]
                        source_name: [ spec, sourceRef, name ]
      enabled: true

    kubelet:
      enabled: true

    kubeApiServer:
      enabled: true

    kubeProxy:
      enabled: false

    coreDns:
      enabled: true

    kubeControllerManager:
      enabled: true
      service:
        selector:
          component: kube-apiserver
      vmScrape:
        spec:
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: https
              tlsConfig:
                insecureSkipVerify: true

    kubeEtcd:
      enabled: true
      service:
        selector:
          component: kube-apiserver
        port: 2381
        targetPort: 2381
      vmScrape:
        spec:
          endpoints:
            - scheme: http

    kubeScheduler:
      enabled: true
      service:
        selector:
          component: kube-apiserver
      vmScrape:
        spec:
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: https
              tlsConfig:
                insecureSkipVerify: true

    alertmanager:
      enabled: true
      config:
        route:
          receiver: "discord-infra"
          group_by: ["alertgroup", "job"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h
          routes:
            - receiver: 'healthchecksio'
              matchers:
                - alertname =~ "InfoInhibitor|Watchdog"

        receivers:
          - name: "discord-infra"
            discord_configs:
              - webhook_url: 'replacedfromvalues'
                username: '${DOMAIN}'
                title: |-
                  [{{ .Status | toUpper -}}
                   {{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{- end -}}
                  ]
                  {{ if ne .Status "firing" -}}
                  :white_check_mark: 
                  {{- else if eq .CommonLabels.severity "critical" -}}
                  :x:
                  {{- else if eq .CommonLabels.severity "warning" -}}
                  :warning:
                  {{- else if eq .CommonLabels.severity "info" -}}
                  :information_source:
                  {{- else -}}
                  :question:
                  {{- end }}
                message: |
                  {{ range .Alerts }}
                  {{- if .Annotations.summary }}
                  Summary:  {{ .Annotations.summary }}
                  {{- end }}
                  {{- if .Annotations.description }}
                  Description: {{ .Annotations.description }}
                  {{- end }}
                  {{- end }}
          - name: "null"
          - name: "discord-info"
            discord_configs:
              - webhook_url: 'replacedfromvalues'
                username: '${DOMAIN}'
                title: |-
                  [{{ .Status | toUpper -}}
                   {{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{- end -}}
                  ]
                  {{ if ne .Status "firing" -}}
                  :white_check_mark: 
                  {{- else if eq .CommonLabels.severity "critical" -}}
                  :x:
                  {{- else if eq .CommonLabels.severity "warning" -}}
                  :warning:
                  {{- else if eq .CommonLabels.severity "info" -}}
                  :information_source:
                  {{- else -}}
                  :question:
                  {{- end }}
                message: |
                  {{ range .Alerts }}
                  {{- if .Annotations.summary }}
                  Summary:  {{ .Annotations.summary }}
                  {{- end }}
                  {{- if .Annotations.description }}
                  Description: {{ .Annotations.description }}
                  {{- end }}
                  {{- end }}
          - name: "healthchecksio"
            webhook_configs:
              - url: 'replacedfromvalues'
                # dont send resolved alerts to healthchecks.io
                send_resolved: false
  valuesFrom:
    - kind: Secret
      name: discord-webhook
      valuesKey: token
      targetPath: alertmanager.config.receivers[0].discord_configs[0].webhook_url
    - kind: Secret
      name: discord-webhook
      valuesKey: info
      targetPath: alertmanager.config.receivers[2].discord_configs[0].webhook_url
    - kind: Secret
      name: alertmanager
      valuesKey: HEALTH_CHECKS_IO_URL
      targetPath: alertmanager.config.receivers[3].webhook_configs[0].url
