kind: VMProbe
apiVersion: operator.victoriametrics.com/v1beta1
metadata:
  name: &name prowlarr
  namespace: homelab
spec:
  interval: "30s"
  module: http_2xx
  jobName: *name
  vmProberSpec:
    url: blackbox-exporter.observability.svc.cluster.local:9115
    path: /probe
    scheme: http
  targets:
    staticConfig:
      targets:
        - http://prowlarr.homelab.svc.cluster.local:9696
      labels:
        name: Prowlarr
        category: Arr Suite
