[env]
KUBECONFIG = "{{config_root}}/bootstrap/talos/clusterconfig/kubeconfig"
TALOSCONFIG = "{{config_root}}/bootstrap/talos-new/prod-talos/talosconfig"
SOPS_AGE_KEY_FILE = "/home/rize/.ssh/key.txt"

[tools]
flux2 = "2.9.2"
kubectl = "1.35.3"
sops = "3.13.3"
talosctl = "v1.12.9"
terraform = "1.15.8"
yq = "4.53.3"
