[env]
KUBECONFIG = "{{config_root}}/bootstrap/talos/clusterconfig/kubeconfig"
TALOSCONFIG = "{{config_root}}/bootstrap/talos-new/prod-talos/talosconfig"
SOPS_AGE_KEY_FILE = "/home/rize/.ssh/key.txt"

[tools]
just = "1.50.0"
kubectl = "1.35.3"
sops = "3.12.2"
talhelper = "3.1.7"
talosctl = "1.12.0"
terraform = "1.14.8"
yq = "4.53.2"
