[env]
KUBECONFIG = "{{config_root}}/bootstrap/talos/clusterconfig/kubeconfig"
TALOSCONFIG = "{{config_root}}/bootstrap/talos/talosconfig"
SOPS_AGE_KEY_FILE = "/home/rize/.ssh/key.txt"

[tools]
kubectl = "1.35.3"
sops = "3.12.2"
talhelper = "3.1.6"
talosctl = "1.12.5"
yq = "4.52.4"
