# https://taskfile.dev

version: '3'

tasks:
  kubectl:drain:
    prompt: Drain controlplane-hyd-1?
    cmd: kubectl drain controlplane-hyd-1 --ignore-daemonsets --delete-emptydir-data

  talos:upgrade:
    prompt:
      - Do you want to upgrade Talos?
    cmds:
      - task: talos:genconfig
      - task: kubectl:drain
      - task: talos:apply-config
      - task: talos:upgrade-image-reboot
      - cmd: kubectl uncordon controlplane-hyd-1

  talos:apply-config:
    cmds:
      - talosctl apply-config --nodes 10.0.0.11 -f bootstrap/talos/clusterconfig/oracle-hyd-cluster-controlplane-hyd-1.yaml

  talos:genconfig:
    dir: ./bootstrap/talos
    cmd: talhelper genconfig

  talos:upgrade-image-reboot:
    prompt:
      - You are going to upgrade the talos image. Continue?
    cmds:
      - talosctl upgrade --nodes 10.0.0.11 --wait --debug -m powercycle --image $(talhelper genurl installer)

  bootstrap-flux:
    cmds:
      - kubectl get ns flux-system || kubectl create ns flux-system
      - |
        kubectl -n flux-system get secret sops-age || kubectl create secret generic sops-age \
          --namespace=flux-system \
          --from-literal=age.agekey="$(infisical secrets get TF_VAR_SOPS_AGEKEY --env=prod --projectId=201b912b-40de-44bf-bb83-ab1bc77554b7 --plain)"
      - |
        infisical run --env=prod --projectId=201b912b-40de-44bf-bb83-ab1bc77554b7 -- flux bootstrap github \
          --owner=navaneeth-dev \
          --repository=oracle-ops \
          --branch=main \
          --personal \
          --path=k8s/clusters/oracle
