apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  # Victoria Metrics dev secrets
  - dev-secrets/victoria-metrics-alertmanager.yaml
  - dev-secrets/victoria-metrics-discord-webhook.yaml

patches:
  # Authentik dev serverName via Flux Kustomization patches
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: authentik
        namespace: flux-system
      spec:
        patches:
          - patch: |-
              apiVersion: postgresql.cnpg.io/v1
              kind: Cluster
              metadata:
                name: authentik
                namespace: authentik
              spec:
                plugins:
                  - name: barman-cloud.cloudnative-pg.io
                    isWALArchiver: true
                    parameters:
                      barmanObjectName: ovhcloud
                      serverName: authentik-dev
              
                  - name: barman-cloud.cloudnative-pg.io
                    isWALArchiver: true
                    parameters:
                      barmanObjectName: r2
                      serverName: authentik-dev
            target:
              kind: Cluster
              name: authentik
              namespace: authentik
    target:
      kind: Kustomization
      name: authentik
      namespace: flux-system
