apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  # Replace victoria-metrics secrets with dev versions
  - path: dev-secrets/victoria-metrics-alertmanager.yaml
    target:
      kind: Secret
      name: alertmanager
      namespace: observability
  - path: dev-secrets/victoria-metrics-discord-webhook.yaml
    target:
      kind: Secret
      name: discord-webhook
      namespace: observability
  # Patch authentik cluster config
  - path: patches/authentik-disable-backup.yaml
    target:
      kind: Cluster
      name: authentik
  - path: patches/authentik-reduce-storage.yaml
    target:
      kind: Cluster
      name: authentik
