apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  # Replace victoria-metrics secrets with dev versions
  - path: dev-secrets/victoria-metrics-alertmanager.yaml
    target:
      kind: Secret
      name: alertmanager
      namespace: observability
  - path: dev-secrets/victoria-metrics-discord-webhook.yaml
    target:
      kind: Secret
      name: discord-webhook
      namespace: observability
  # Temporarily disable authentik
  - patch: |-
      $patch: delete
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: authentik
        namespace: flux-system
    target:
      kind: Kustomization
      name: authentik
      namespace: flux-system
