apiVersion: v1
kind: Secret
metadata:
    name: backstage-envs
    namespace: backstage
stringData:
    AUTH_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:MxpoRKu5PgzD49dIx2Y7fLVRRIo=,iv:wFCiJNj9fful/qO7ASTdBwX7gbyN4hRJa8pkIOkQPxM=,tag:DcJXMTgeXdzSDmTyVBbA2w==,type:str]
    AUTH_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:PahrQViW09/b03ughwIifWd+TAoIy9d5k4uGZtgK5KxKCptyvjjQfw==,iv:rEaQj9WQ+n8i52Jl83wkQ9IzFfvV/2XvAC3W4j+Z/HA=,tag:5DgXbpzX9RDc7vVkNTPG9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVzJYaGUrZ1NZblQyaVdU
            S3BzV3NDeVlHSDJtQWRhYkxUVXBTS2VrMGtvCk1CblN1SnNkemlQNmQ3MFViOFRa
            L3l5SzIzRnlHU0dHRjU0a2l3bEdGWWcKLS0tIGZsZjBWR3N1RERHTXBSaEM3YS9u
            MTZ6UnVjUEpxVDgzbDlQMHkrWUNOUEUKp6ROSyiPf/wYh2tEqqfk+vS/bdzVIS1m
            xonXszln842jDhHZLkjR9suHqb1PgqcqvXUPPodAYe+TDWlf67mBRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T07:34:59Z"
    mac: ENC[AES256_GCM,data:lNJkDFzDk31FUZp5AXF4wUfoBeyyO+VKQtFp/YnEcslVl3C6AKmVqX+AX7P8PXbuvZja9j3wsQs4raUko6dAFpmQnpN02l+BSDOvjmCyjgAYKk1rkf+X6RymhkPvSkm+gszTCfNtu2Vpx/tqo6R6i1lUrvCNegi35bKVXq+5U3c=,iv:aJV7/dca+LrQiapC+pHumQysOdInOncqES9Y4580CUo=,tag:QcpFKxhYs/TWJL3pEmJ+Yg==,type:str]
    version: 3.13.1
