apiVersion: kro.run/v1alpha1
kind: WebAppWithDatabase
metadata:
  name: backstage
  namespace: backstage
spec:
  name: backstage
  replicas: 1
  image: ghcr.io/navaneeth-dev/backstage:v0.0.4 # {"$imagepolicy": "backstage:backstage"}
  hostname: backstage.${DOMAIN}
  port: 7007
  env:
    - name: BASE_URL
      value: https://backstage.${DOMAIN}
