---
apiVersion: kro.run/v1alpha1
kind: WebAppWithDatabase
metadata:
  name: backstage
  namespace: backstage
spec:
  name: backstage
  replicas: 1
  image: ghcr.io/navaneeth-dev/backstage:main # {"$imagepolicy": "flux-system:default"}
  hostname: backstage.${DOMAIN}
  port: 7007
