apiVersion: v1
kind: Secret
metadata:
    name: wireguard-secrets
    namespace: homelab
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:fSpM7+zZt+3iY4AQDDN1Uzg6tq8peWQ+EB9kuQNWiWcJIXA3Pf2wkR3MYkU=,iv:1o8U8wlLKpn0qe1GiBxfQuAPs6xudRroEl1a4pS9U0o=,tag:8Yij9ew9y+9Am+ZrZq4mkg==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:hlDndePH1y/5AZUw+6ssfEB41bHbHW6Qh6/oleJnEGIcOGsyvvRIo+ZADxQ=,iv:Yzr0gYENefC3QjnxgD5cAN9rCVT3D+4ZKmsxJe6Dq3A=,tag:cA1GQdOGYtmtXzViF4K9lg==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:ZADRJWg=,iv:9cBLWuBxvadnsC6qtaQkpPW0jBOVTjweejjBZ5dXp+E=,tag:LYEMmVqKiKuxGRcL7pcLoQ==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:Pk423054an6k+uQQ,iv:X8Kov7t/ZGG2fLXxmvt11jehdK/S0rdkZqQDYAcnoCg=,tag:vIGT3DU5Vqn8Cdg7Jowj/w==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:UNKdrIScfv+HTp2Nmw==,iv:mFfVWDmJ7DzSDe9ZMsaQsFbB0eX+Q1kGV1Z2FwuzCKQ=,tag:tKwGzBvK1aKCo3YxYaqJVA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:oTH1NbZJcRXz6nDAMyEYZy1SnVjyDXmFXLRravtBvChJcpg+4a6v0uD5bSA=,iv:qrqKMmVxYt84VMZhiaaEXXKQVq3R/qMUgYhH3E508XQ=,tag:PbSz2RwsbQQU3JViJZTCbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaXdkMmdUdk9vdVRlUnRn
            OTFjRk5zL3BEVzB5b1hSQ0xrRk5NZGxnNWhRCk5ISXhKSmVzejFIZFRIZkVuRUcw
            T2MwVExVMXVUdDJGVFhNcUlYZXRNVUEKLS0tIEpUcVVTOEhNUjVSVHZ0RkQ2OUUz
            WElMN2lyZUxwUDNPU1UreW03TW9KWDgKKI1FRUg8cUX0pxZFmSS0mFWmwnXSikDj
            N5Cl83rVTf9Oy5vPKawZbYxZroHkto3Jv/R92dBQIb2rmQbCn3gM4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T10:39:25Z"
    mac: ENC[AES256_GCM,data:EvtPt3uoX9lAxvBqlCvlsXvUUOdcuoVcqA1sjNUT/0zDOa8JOGhAbeA5LDEcTwOGMnWexpQ0yFuOJ+llPMTtEWg/QjBjhza1xXrJ12RZcqXueC8f1VAXVPM6JeYgIVhYA15q16t1goN1rDvQvAAbXMbW0E8W/ZcTcqknzrfZpCQ=,iv:J6VrTrKfX7cYRbdKH5rBUGqT2ZqSMCin6NZ6ceC7DuY=,tag:fnPtUqbkWxSPsMH9BBeqkg==,type:str]
    version: 3.13.1
