apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: web-app-with-db
  namespace: kro-system
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  schema:
    apiVersion: v1alpha1
    kind: WebAppWithDatabase
    spec:
      name: string
      image: string
      replicas: integer | default=1
      hostname: string
      port: integer | default=80
      env: "[]object"
    status:
      deploymentConditions: ${deployment.status.conditions}
      availableReplicas: ${deployment.status.availableReplicas}

  resources:
    - id: ns
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: ${schema.spec.name}

    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name} # Use the name provided by user
          namespace: ${schema.spec.name}
        spec:
          replicas: ${schema.spec.replicas} # Use the replicas provided by user
          selector:
            matchLabels:
              app: ${schema.spec.name}
          template:
            metadata:
              labels:
                app: ${schema.spec.name}
            spec:
              containers:
                - name: ${schema.spec.name}
                  image: ${schema.spec.image} # Use the image provided by user
                  ports:
                    - containerPort: ${schema.spec.port}
                  env:
                    - name: POSTGRES_HOST
                      valueFrom:
                        secretKeyRef:
                          name: ${schema.spec.name}-superuser
                          key: host

                    - name: POSTGRES_PORT
                      valueFrom:
                        secretKeyRef:
                          name: ${schema.spec.name}-superuser
                          key: port

                    - name: POSTGRES_USER
                      valueFrom:
                        secretKeyRef:
                          name: ${schema.spec.name}-superuser
                          key: username

                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: ${schema.spec.name}-superuser
                          key: password

                    - name: BASE_URL
                      value: ${schema.spec.hostname}

    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${schema.spec.name}-svc
          namespace: ${schema.spec.name}
        spec:
          selector: ${deployment.spec.selector.matchLabels} # Use the deployment selector
          ports:
            - protocol: TCP
              port: 80
              targetPort: ${schema.spec.port}

    - id: httproute
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: ${schema.spec.name}
          namespace: ${schema.spec.name}
        spec:
          parentRefs:
            - name: reverse-proxy
              namespace: envoy-gateway-system
          hostnames:
            - '${schema.spec.hostname}'
          rules:
            - backendRefs:
                - name: ${service.metadata.name}
                  port: 80

    - id: db
      template:
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: ${schema.spec.name}
        spec:
          instances: 1
          storage:
            size: 1Gi
          enableSuperuserAccess: true
