genconfig:
    sops -d secrets.sops.yaml > secrets.yaml
    talosctl gen config --with-secrets secrets.yaml controlplane-rizexor-prod1 https://140.245.250.113:6443 \
      --kubernetes-version 1.35.0 --talos-version 1.12.0 \
      --config-patch @patches/cert-approver.yaml --config-patch @patches/hostdns.yaml \
      --config-patch @patches/oracle-ntp.yaml --config-patch @patches/topolvm.yaml \
      --config-patch @patches/scheduling.yaml --config-patch @patches/cilium.yaml \
      --config-patch @patches/cert-sans.yaml --config-patch @patches/monitoring.yaml --config-patch @multidoc/volume.yaml \
      --force
    talosctl config endpoint 140.245.250.113 --talosconfig talosconfig
    rm secrets.yaml

reboot:
    talosctl reboot -n 10.0.0.11

applyconfig:
    talosctl apply-config -f controlplane.yaml -n 10.0.0.11
    rm controlplane.yaml worker.yaml

kubeconfig:
    talosctl kubeconfig ./kubeconfig --nodes 10.0.0.11
