apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/components/-
        value: ../../../../../components/volsync-dev
    target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: grafana
      namespace: flux-system
