LB_IP := `terraform -chdir=../infrastructure/ output -raw nlb_public_ip`
CP1_IP := `terraform -chdir=../infrastructure/ output -raw instance_public_ip`
NODE_IP := "10.0.0.11"

KUBERNETES_VERSION := "1.35.0"
TALOS_VERSION := "1.12.0"

genconfig:
    sops -d secrets.sops.yaml > secrets.yaml
    talosctl gen config --with-secrets secrets.yaml controlplane-rizexor-prod1 https://{{ LB_IP }}:6443 \
      --kubernetes-version {{ KUBERNETES_VERSION }} --talos-version {{ TALOS_VERSION }} \
      --config-patch @patches/cert-approver.yaml --config-patch @patches/oracle-ntp.yaml \
      --config-patch @patches/hostdns.yaml --config-patch @patches/topolvm.yaml \
      --config-patch @patches/scheduling.yaml --config-patch @patches/cilium.yaml \
      --config-patch @patches/cert-sans.yaml --config-patch-control-plane @patches/monitoring.yaml --config-patch @multidoc/volume.yaml \
      --force
    talosctl config endpoint {{ LB_IP }} --talosconfig talosconfig
    talosctl config endpoint {{ CP1_IP }} --talosconfig talosconfig
    #rm secrets.yaml

reboot:
    talosctl reboot -n {{ NODE_IP }}

applyconfig:
    talosctl apply-config -f controlplane.yaml -n {{ NODE_IP }}
    rm controlplane.yaml worker.yaml

kubeconfig:
    talosctl kubeconfig ./kubeconfig --nodes {{ NODE_IP }}

# For documentation purpose
cilium-install:
    helm template \
        cilium \
        cilium/cilium \
        --version 1.18.0 \
        --namespace kube-system \
        --set ipam.mode=kubernetes \
        --set kubeProxyReplacement=false \
        --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
        --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
        --set cgroup.autoMount.enabled=false \
        --set cgroup.hostRoot=/sys/fs/cgroup \
        --set envoy.enabled=false --set operator.replicas=1 > .cilium.yaml
