LB_IP := `terraform -chdir=../infrastructure/ output -raw nlb_public_ip`
NODE_IP := "10.0.0.11"

KUBERNETES_VERSION := "1.35.0"
TALOS_VERSION := "1.12.0"

genconfig:
    sops -d secrets.sops.yaml > secrets.yaml
    talosctl gen config --with-secrets secrets.yaml controlplane-rizexor-prod1 https://{{ LB_IP }}:6443 \
      --kubernetes-version {{ KUBERNETES_VERSION }} --talos-version {{ TALOS_VERSION }} \
      --config-patch @patches/cert-approver.yaml --config-patch @patches/hostdns.yaml \
      --config-patch @patches/oracle-ntp.yaml --config-patch @patches/topolvm.yaml \
      --config-patch @patches/scheduling.yaml --config-patch @patches/cilium.yaml \
      --config-patch @patches/cert-sans.yaml --config-patch @patches/monitoring.yaml --config-patch @multidoc/volume.yaml \
      --force
    talosctl config endpoint {{ LB_IP }} --talosconfig talosconfig
    #rm secrets.yaml

reboot:
    talosctl reboot -n {{ NODE_IP }}

applyconfig:
    talosctl apply-config -f controlplane.yaml -n {{ NODE_IP }}
    rm controlplane.yaml worker.yaml

kubeconfig:
    talosctl kubeconfig ./kubeconfig --nodes {{ NODE_IP }}
