apiVersion: v1
data:
    token: ENC[AES256_GCM,data:6jnXcQS21F7AhsuSqfJz8rBTLvEAiEaJ1FtKA80ZAP6nXKgPoDcwD7DjKYHRHT/8EIobbWUAQlQZu0m7hfk6rUSxoaTEF9PiMtA8UInEbGlYuLQC5neHNhWRvtrTiGG1Cgxor482NEH+RcFiKmg51J+WnhROUXYK/mkFE/RiwD81nafHo6PTEOkEt7aZZvS3RXOjqNdSLdvt1Lly6taOQRwRsM4=,iv:x5A+OXD9xnLU2WdiVgxpzsf5Gny53DpVEcKZVzr5vbI=,tag:mtSbnBKL/xurIlsqxqeQTQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: discord-webhook
    namespace: observability
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTWpCNGlJa2VWRndFSytC
            WlhBc1hJZkRTb2tiUnNWL0NSTHBBaXpnNkM4ClFLemVmN0FIYldzMW1XRkJxc2dp
            Uzl5amU2U1hQMWV1TzRGYm0zYXd3RFkKLS0tIGZSbTlWNEx0NncwWVNzM2ZOUDA0
            M0hnOTRTRGJCZENDd3BEeFVLVUc3NkkKPQD5ROiVfIycDiZFWnK9gqKVWQc4Zq7+
            0clh/NvxJ1qD5qTLI2Eg3JjvxFtK2aNBymRkCos/Vrgf2HljOmIG3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-23T16:34:40Z"
    mac: ENC[AES256_GCM,data:hOt0vj+Ni4r8Z5jnv1IS44p9pOywdhK3Xf8z4FDOor2V2H4rNsdY2OXuKIq/89I043z7iv8jx6tV+B7j/j69tD1tSNGxqps5WqT7jG7w9dzVf1g1HuzE0W1BmXH2QflhL84m6QQAxeGem2P6LMNJlltS4I8ZtvcoDsdpOssojJE=,iv:lEPyOWN9e23RKxfRu8XPxFAFg4ZTWERBkRwxYzIxpks=,tag:LW39p07rVVgs2LVujxlp7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
