apiVersion: v1
kind: Secret
metadata:
    name: wireguard-secrets
    namespace: homelab
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:Jufa0X5RNrWK4Wy60wwG0imtw00HYTSFaj0qWOR8Q8mUp5DAxtPUCOb/4wQ=,iv:YOVmtr77DtnAcgDxk0yd6mFGvsZYBCmfnUpGkdgzEGY=,tag:SA4zb5Dsat7gd0KUVn8f6A==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:y3DbIZ9yZeD2m3g0o+yMxFpip4GsfwcCp8FkCiLNbVLlFjAOIk4uSWtD2DY=,iv:/Dw+DKNHlBUEj3+iX9AEz5bIg8tU5lSPQXmVFfXe/YY=,tag:lfSobe6rAv/InlLocSfFFQ==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:ZADRJWg=,iv:9cBLWuBxvadnsC6qtaQkpPW0jBOVTjweejjBZ5dXp+E=,tag:LYEMmVqKiKuxGRcL7pcLoQ==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:Pk423054an6k+uQQ,iv:X8Kov7t/ZGG2fLXxmvt11jehdK/S0rdkZqQDYAcnoCg=,tag:vIGT3DU5Vqn8Cdg7Jowj/w==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:ZWrYsx1ocrGHSJMWdg==,iv:JItyBSxGIYLwHexcCwAVOn0r/yhw98bUJWvQGLQRDvU=,tag:cpaSe2maEIzHOq6aG/CQ3A==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:oTH1NbZJcRXz6nDAMyEYZy1SnVjyDXmFXLRravtBvChJcpg+4a6v0uD5bSA=,iv:qrqKMmVxYt84VMZhiaaEXXKQVq3R/qMUgYhH3E508XQ=,tag:PbSz2RwsbQQU3JViJZTCbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaXdkMmdUdk9vdVRlUnRn
            OTFjRk5zL3BEVzB5b1hSQ0xrRk5NZGxnNWhRCk5ISXhKSmVzejFIZFRIZkVuRUcw
            T2MwVExVMXVUdDJGVFhNcUlYZXRNVUEKLS0tIEpUcVVTOEhNUjVSVHZ0RkQ2OUUz
            WElMN2lyZUxwUDNPU1UreW03TW9KWDgKKI1FRUg8cUX0pxZFmSS0mFWmwnXSikDj
            N5Cl83rVTf9Oy5vPKawZbYxZroHkto3Jv/R92dBQIb2rmQbCn3gM4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T10:37:19Z"
    mac: ENC[AES256_GCM,data:3E/LmAjAH/WNOpcUi5HTTCwu5Bh9nCFt3k07HevJzNVcE9aVEi9yjX2F7AVwZSRqKB/trKV20xgIhJsNM4wdWXEpdkTejomZ81qyH450UXa040sKY49vczE7ZjRCeP/TrOkzvHNEK/UK8PPrFDadjkPkraG6jaAvgtNtintz51Q=,iv:WHKu/8Ym0mOMmhffl7h1hF5ZEIhrCXCrp/r+ss/pOqg=,tag:uwqFRzIUgNN7LOeqVkuHmw==,type:str]
    version: 3.13.1
