apiVersion: v1
kind: Secret
metadata:
    name: alertmanager
    namespace: observability
stringData:
    HEALTH_CHECKS_IO_URL: ENC[AES256_GCM,data:RWagYHZwB4Pjvq/U+bx19HT/dRSQn/kFo353nL7bT6ze0FuHxCy1zhw0jUB0Ifl/GD1UdpIbwqM=,iv:rUJMuOteeSoOhg3kbIzyGqTXhjjkXUw4OxsuwUuhFGc=,tag:y3LK5u/Avz9+Vw66pESnyQ==,type:str]
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUEdPZ1laRDZidWRTVWhL
            ZElQMy83Q0h4d1FSUjkxamJDWWY5SWd4Z2xjClhUSllZTVJBTmFHWHFXekhOMUJr
            eHpva1dOYkNWcXJNK3FQM3dXS0tFcU0KLS0tIGQzREhUTHVYcU02MzliMUJKN2ZW
            TmdtUUhhcURrbCtOR0FoU2NTSWpDbDgKObUaGuYcUyKvSVDMFZJLmVwgd9nEeBAK
            2Fr1iCk868DNKob7v4pMb2A6GJYPEDac5mhdbXbRCgKoqISt3YYfsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T14:09:44Z"
    mac: ENC[AES256_GCM,data:2H3nPoIUB16SZMZ+e3s90pO6digt0ZBl+GXPCqcdBWIe9zGTGHWU04Ua0Qb/ValzmJRh77dhQFcKmUrrQ6bimPTY7SuUEkM74+sbNIhI/jl2pbjG4GgpKxMNp1E+NoiBJS5r3tUQlpjJIvojz5oT6hW+0wQb0FdnF9UxY/haU3g=,iv:nc8Ac8Ebai4sySm2R8SSU0Mirm+Ye4bS1dyMMekby6A=,tag:Z66PPJ9HCIu1WhZpCON0tw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
