apiVersion: v1
kind: Secret
metadata:
    name: flux-alerts-discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:4WB1NYhBhMmkcE5WivsIT9nc0VjSnTz5aqjjezdA6FU9YId3oNWm6pGAN22qy1KkBQrQdtH/NxchFAZ50FYpXaVLkH6C9DDulq5L2H+nUtEaX3tqhXE9pvsXOPjTg+ny+y9FC5kO+q8u9bItLIU0piZ+M5KatqDgEg==,iv:OwCXFOWPnYjJRe6Lp2iiwqc239LKcrC1/zA5t36j5nY=,tag:yE4c6Ti5QucCd3oBbLMrzw==,type:str]
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWGZvczUwVzNVRVBscTdM
            dENqRWxDWTVvNkxlUXZDQmdsOE11NmpnTEJ3Ck9nbXh5NWpuZmdKaGwxR2h6dFk0
            M3ZMZ3NHQTNGaWtIdkVTTk5nUW5OekUKLS0tIC84Slp5MlBvTHFBcHFYZ0MydElO
            MzM5ZmRVN2pSaXg2a09RRW8xWEdDS28KF90Y1UjqjmRQvYfNuyFBysDtQuheR0gC
            ExznCmNNinFj/To7e7t9rLuOgUo+DE+DdS0B8Nzt6+NgI+TOUo95ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T14:22:16Z"
    mac: ENC[AES256_GCM,data:omg0qyxd1Oxl1+nKEQKDLF23b3Ikk3H4ILDDDW1W/4gmym18/2d1imOSrjWaKgRRlQLl/B+5Myil+9UnIk/D23/y84XgSp4JiDD1KJYNuKlCQDSt3RMEinXXaxKu9PK33zLTbnYCsJjvcAXJvBldur9jREmk6p70OjoNGXHGPJk=,iv:RrMw8jtiXprEr0I8O+eiH3zJhKAhab/rxsIRdbUwu0k=,tag:NYIBHCeJFW9LjH8zmZKq/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
