set shell := ["bash", "-c"]

talos_version := "1.12.6"
arch := "arm64"
image_url := "https://factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/v" + talos_version + "/oracle-" + arch + ".qcow2"

all: prepare-image tf-init tf-apply

[working-directory: "files"]
download-image:
    @if [ ! -f oracle-{{arch}}.qcow2 ]; then \
        echo "Downloading {{image_url}}..."; \
        wget -O oracle-{{arch}}.qcow2 {{image_url}}; \
    else \
        echo "Image oracle-{{arch}}.qcow2 already exists, skipping download."; \
    fi

[working-directory: "files"]
prepare-image: download-image
    if [ -f oracle-{{arch}}.raw.xz ]; then \
        xz --decompress ./oracle-{{arch}}.raw.xz; \
    fi

    if [ -f oracle-{{arch}}.raw ]; then \
        qemu-img convert -f raw -O qcow2 oracle-{{arch}}.raw oracle-{{arch}}.qcow2; \
        rm oracle-{{arch}}.raw; \
    fi
    
    # Create OCI archive (requires oracle-{{arch}}.qcow2 and image_metadata.json)
    tar zcf oracle-{{arch}}.oci oracle-{{arch}}.qcow2 image_metadata.json
    
    # Cleanup intermediate (keeping qcow2 to avoid re-download)
    # rm oracle-{{arch}}.qcow2

tf-init:
    terraform init

tf-apply:
    terraform apply

[working-directory: "files"]
clean:
    rm -f oracle-{{arch}}.oci

[working-directory: "files"]
clean-all: clean
    rm -f oracle-{{arch}}.qcow2 oracle-{{arch}}.raw.xz oracle-{{arch}}.raw.zst oracle-{{arch}}.raw
