kind: VMProbe
apiVersion: operator.victoriametrics.com/v1beta1
metadata:
  name: grafana
  namespace: homelab
spec:
  interval: "30s"
  module: http_2xx
  jobName: grafana
  vmProberSpec:
    url: blackbox-exporter.observability.svc.cluster.local:9115
    path: /probe
    scheme: http
  targets:
    staticConfig:
      targets:
        - http://grafana-service.observability.svc.cluster.local:3000
      labels:
        name: Grafana
        category: Observability

