apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: ipv6-proxy
  namespace: envoy-gateway-system
spec:
  ipFamily: IPv4
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
                - name: http-80
                  port: 80
                  nodePort: 32579
                - name: https-443
                  port: 443
                  nodePort: 31258
