apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: primary
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-rw.keycloak.svc.cluster.local
    usernameSecret:
      name: keycloak-app
      key: username
    passwordSecret:
      name: keycloak-app
      key: password
#  http:
#    tlsSecret: example-tls-secret
#  hostname:
#    hostname: test.keycloak.org
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
