---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name velero
  namespace: *name
spec:
  interval: 30m
  dependsOn:
    - name: victoria-metrics
      namespace: observability
  chart:
    spec:
      chart: *name
      version: 11.1.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: *name
        namespace: *name
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
  
