# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name homepage
  namespace: homepage
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.4.6
            env:
              HOMEPAGE_ALLOWED_HOSTS: &host "start.${DOMAIN}"
            resources:
              requests:
                memory: 10Mi
                cpu: 10m
              limits:
                memory: 200Mi

    serviceAccount:
      homepage: {}

    service:
      main:
        ports:
          http:
            port: 3000

    route:
      internal:
        hostnames: [*host]
        parentRefs:
          - kind: Gateway
            name: reverse-proxy
            namespace: envoy-gateway-system

    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml