apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:C4LxK6Hc9mfG32PbmlySlxhcAqIo7atvxBihYKNPwx8PmuC/PCUD6rgkKrFdsuf2kRF0iERzjc7ZC2NQe6CSNZTiJIqvYSP1CToG0Qk=,iv:ukXHK3HrYo3I0X1n6KO32ulzUYofekoKj41D1xnlmwE=,tag:+f9x6jpt6X7cRchk7ZiCDA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:IHKZdWxQWRsgv68pxBcwWXi+7S5YaUf99usB5HhIm4g=,iv:Yxnc4xC1ZMc6tjiJQjn2lAIcLazn5Hws2D1Q/oi/87c=,tag:LaKy2CPrzfLPkh+8oKHbDw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:kCMRAScqWKjr8Bx6emvPULOJfWA2/bg6SBOGPWQTeYQ=,iv:ZPI0l1jVGRXWk0MvkDhZ6LlsYEtQe879MP3DTpfN1s0=,tag:M+fgEA6o1rxYP7CCVcsAAA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PErEVV552ywUGp9Wv/f4+gp0LQC95bMLMYIl55sS3nk=,iv:CiZ2A1QPcy8J8D1aWVpxvhC11w0SWNlh2v9N4Wnh/8U=,tag:SP+fePOMDMhO7rlOyj7gHg==,type:str]
sops:
  age:
    - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK3lEMk5DenVNOEFRUTVa
        Ri9iZGFTOVM5emovZmljZWpnbHJ4MTZIZUg0ClFrOU5DSUNnc3oxSVlPelVLSjVW
        djl1aHJqbnlTbEVFaTcyYTl2SnNxekEKLS0tIEI3TzhGQUFaZlFwTXgzVVZsOEJM
        em5XRityVkdxTTZjVnpXU3Z1aXd2UTAKMd1JvA0WwEoLsdaCGyajrAjxB++W6pYx
        L9FDa1NvU7dkEMzqPD9rpXAOGaOSiWWYVMYu4+1VF778Li+llKoDHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T08:37:17Z"
  mac: ENC[AES256_GCM,data:4csNZPChkJXvnkmqeZ0rO5CumN9So+0N81xcFVf5BihPbSxdzGaoSc7VMGEsqj0km34MFzl9QdfuCwHP9AsuLrwnN60J3GKORMMlfDDyYfLmAcgfW2hqgj6JRUsvBWu0y3GtFc1+89t1GG+T3ov99rzQc4J0ewaon5cIiv/aqEA=,iv:RqXniQ3w4uZmHQBDLQXWOz78DUTTNDFrED71RT7bBU0=,tag:VtfVGevslqe1WXJVWCjxZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
