apiVersion: v1
kind: Secret
metadata:
    name: alertmanager
    namespace: observability
stringData:
    HEALTH_CHECKS_IO_URL: ENC[AES256_GCM,data:1UckPeU31cEBv13v3Dfe4HuIXXRquaXLElJobzMQ+n2i2xSZcKr04qnkOA+gDylspBk=,iv:jwLzJSO+pjmhAPVCVmfoAtqibUhFSoTKZKWjroaRvK8=,tag:49Q4NfiLFQCNWMJv/rE1Jg==,type:str]
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdzAvSWs0cEdhUmg1NFh2
            aEV6bHVrU1AybDB2bHBqUVNMNHd4U0daUEVRCmdQVE5WekZlTzhwOERMelVKek9N
            ZitOOVlaRFBsc0xlMUhJME9wU1cxZFkKLS0tIHhhZlIyOVNIQnRsQnRhcG1iVldB
            M3FETEFGTVpGdDlzUTQxaEdBK3hlTFEKRFhNkzwecJ8JUlLo+LubhYfHJx/M1BZE
            aST8b1qKEuDMN0SPTLXngWCKBEp7dpWavycwG83tGCinGlH/6ZPimw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T06:43:45Z"
    mac: ENC[AES256_GCM,data:I2RZ0rlv48Vb2eh5FbDkxFYAtDFJkZkMFP5+9I34x7UXvllP1AJozSwIKdFAuSz7mReKRHgZ2rJIdWBGO0nMHnsbxj1E+kY2tFflOs5P5wZ/GFP2xhUKNRYvj9mWf+TnSOH0XCjIOIhvCWDjootnvG4vy2gN614d20VEM2Q5fSA=,iv:e8qlHHOsmUYA6hDRiKcVOdDnf8ioC0AP+wzo/SV7x/Q=,tag:kbNWewUeipqAGqxvzf4YnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
