---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: authentik-embedded-outpost-timeout
  namespace: authentik
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ak-outpost-authentik-embedded-outpost
  timeout:
    http:
      requestTimeout: 2m
