# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
  namespace: authentik
spec:
  instances: 1
  # disable pod disruption budget for oracle single node
  enablePDB: false

  bootstrap:
    recovery:
      source: source
      recoveryTarget:
        targetTime: "2026-04-04 14:30:00+05:30"
  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: ovhcloud
          serverName: authentik

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: ovhcloud
        serverName: authentik-april-2
  storage:
    size: 2Gi
  monitoring:
    enablePodMonitor: true
