---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: r2
  namespace: authentik
spec:
  configuration:
    destinationPath: "s3://rizexor-oracle-postgres"
    endpointURL: "https://af03f304003ab4ff85fb5677fb1f402b.r2.cloudflarestorage.com"
    s3Credentials:
      accessKeyId:
        name: cloudflare-r2-credentials
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cloudflare-r2-credentials
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip
      maxParallel: 8
    data:
      compression: gzip
      jobs: 2
  retentionPolicy: "31d"
