apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-r2-credentials
    namespace: authentik
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bKkx5hd+OL4L3RvjM5JSVvBN782CoQGopLabDSEtJO4=,iv:ZZ34mkwfwGRdK0cbop57Xz8ru+yHFzjfVNUS/6eHCKk=,tag:s/7xzE0U7ZIQ2NpaOcNFdw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZXjy+dlN2rCNPn3eqTQzIeoWNZLdXOOYODib+CInGEoFZNj6K+pHAeYSt5a0reljLkohF+7MD1sfpAxOCRi3SA==,iv:4MNMDkyoj0TcKCthq+TKQY1BSXRXdrJc2fcyD/GyYwg=,tag:056ZYlULx7uV0r7rGHQ8GA==,type:str]
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZmU2Mm1UcllNdGhoS2xQ
            NVJ1UkhkQ2FBT2lPWEVubVYvZ3BHYUJDZXlzCjVFQzVxTXd6UXlsQXZDYVI2aVFu
            dEo5cUJMN1JsMUhnTDAwaW1VcktBZlEKLS0tIDFsV2g2U3pVQ2lNWGtGeFdGR2RT
            NFMvTERobWNKR3pzUUROa2dnVFE0ZkkKxhj4uIUcjdLCZEfcOLDesIvPPfurhg6r
            /paGkgTOREzRME5TJOgj1a2qQRh0qQnsJFSJ2NHHINZf+2nOI+nXlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T10:32:13Z"
    mac: ENC[AES256_GCM,data:Z29b1EGyFwNDXYFeEsel2BTQScPkE59vqwxCKRJTedC10bEjAbPd30hmYM/1mvuuHsyr/yQkun18YEgstRcPQfSEA/XvZfGc5fvivvgH4KqDKeT5+kdoWNxxbdSPJR3gAhOsgSueHnum5GvcW+a9N3eWfwSrbTJrDGOByNYONWA=,iv:5aDz78DlpekJumCRZciigW3qEYkz9ZGN3oCzMyvNwo4=,tag:SJqcXZ7JFebzsmdNjApuWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
