apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: backstage
  namespace: backstage
spec:
  image: ghcr.io/navaneeth-dev/backstage
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: backstage
  namespace: backstage
spec:
  imageRepositoryRef:
    name: backstage
    namespace: backstage
  policy:
    semver:
      range: "*"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: default
  namespace: backstage
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    push:
      branch: main
  update:
    path: ./k8s
