# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name eg
  namespace: envoy-gateway-system
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: eg
  install:
    crds: CreateReplace
  dependsOn:
    - namespace: observability
      name: victoria-metrics
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
    force: true
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  driftDetection:
    mode: enabled
  maxHistory: 3
  timeout: 30m
  values:
    crds:
      envoyGateway:
        enabled: true