apiVersion: v1
kind: Secret
metadata:
    name: sonarr-ovh-upload-secrets
    namespace: homelab
stringData:
    OVH_ENDPOINT: ENC[AES256_GCM,data:/Qcbe2jmXdLF1QNnU3b52Io6ew0nl7rQi2aa/YtYR9woGvE8vG6lEA==,iv:Lf46CoG2Kj41yIVOt9wW8dHc8nRyk6XH+9Cft0ak2P4=,tag:6oA8XkGmC3mIRqyOMz+6EQ==,type:str]
    OVH_BUCKET: ENC[AES256_GCM,data:f+nrMsxNha/PrFhprg==,iv:o3lG1yboAJbG6KjFTN8QOxfNeehKsR3s2JbFW+nm3WI=,tag:4bP/fFSX9zh3fDd3HAKEqQ==,type:str]
    S3_PREFIX: ENC[AES256_GCM,data:Zuk3fZ5D,iv:mWlYWlvXlVND8fMD9pTvjeLV/RsGg51kyBGq3Cmfdf8=,tag:7XVYctU21hxc9P0X8+k/iQ==,type:str]
    OVH_ACCESS_KEY: ENC[AES256_GCM,data:LS47bPcmwMnYycDKGZVZcMZmmkjl6gfNCA30LwcgUIY=,iv:mnjTGRZ6nUyRTGxEjI0ToNYQPi1bZcPVHr0vvRwpP8Q=,tag:dT9KdGFjtMmePuCFJX0NDg==,type:str]
    OVH_SECRET_KEY: ENC[AES256_GCM,data:Emc0aTHQ45yQfk/7lzHSljXZMP5j12emIsDXv4DIJVY=,iv:LK5s9s9rwJwJsPQc/Iv91LGGucBYgPCIplxlmowwwJc=,tag:aFDlmUiE33nXWjNzlR4hjA==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:VM2akASw9cAFkLVic3wp6A4ID0ozseFNr9kSxb8rRuIs/46PSoGsBaQ6d2CImrXvOidq9h5E+8CNFQFzpnhkBTlMfn/fVfwaM0wXMmnTPTE9Aw7KZ/wRm5Tqrbd7NkdqVIn42j1yfvX8i7qR8W4AW0RLuQf86C0YIw==,iv:vk4aKSuBkmCmpNuktNSCixk+RYp7Lj9dTzBjOSJvuYE=,tag:oXGO9DS88yZq46KFsbHE+Q==,type:str]
    PRESIGN_EXPIRE: ENC[AES256_GCM,data:PKnLPw==,iv:S+pwDMrSJ3Gp6r+fiFuwrMRWzKlrx41U8OEjGZzlbHo=,tag:khMQ9yj3aB6I/FDXRXZOaQ==,type:str]
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBna0VLNHI2Q01keFRTSU4x
            S1hqV25DMWhpV0RFLzJnaTkrSGdSd0gyNDBvCjZOL3lVSlVRUTlHVHkwSzdoM3Jz
            blNjY3JtNmgzK1pSdlFEejNkK3NwQjQKLS0tIDRaa1U1U3l2NnZsTGtVVEd6a1Ft
            SXFuaGlaNUVrclFTQk5FMks2VFdkUkEKDKybSYey1BcJVXLKTJZcgPWyGPYUjwy7
            kIrwZhUhQShKzCAFWtx5lqThBoyr3ajn9lmMNlPER0kGcrSbBof09A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T14:54:44Z"
    mac: ENC[AES256_GCM,data:RwQfMn+EKruHJSnYSxHDWNo466uvUe6g4dzlQfQ9AlJFI4ybGtPAFUBrD47iXHSdBpCzV856RZcPzFMCeu5UNgLvrxbsrnyqB5yJyB67291nvSLSZQ+yU1YG+bEyb/XQB3mQGazK9uXulLJDLGw1fVsI86kDuvMMdgx5mJzRSyo=,iv:wxZWtsIZtytkINGTBz7rtOabVE7ugYqiT1nODner930=,tag:SJizUJJn8gpaCWP8Jwqfog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
