# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name radarr
  namespace: homelab
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      *name:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 5.27.5.10198@sha256:d7af98ace197411f38fcacbdc0bb5530ac5669a27cab9e28889aa531b5a1b536
            env:
              TZ: "${TZ}"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 7878
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  timeoutSeconds: 15
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ "ALL" ] }
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 50m
                memory: 100Mi

    service:
      app:
        primary: true
        controller: *name
        ports:
          http:
            port: *port

    route:
      main:
        enabled: true
        kind: HTTPRoute
        parentRefs:
          - kind: Gateway
            name: reverse-proxy
            namespace: envoy-gateway-system
        hostnames:
          - 'radarr.${DOMAIN}'
        rules:
          - backendRefs:
              - group: ""
                kind: Service
                name: radarr
                port: 7878
                weight: 1
            matches:
              - path:
                  type: PathPrefix
                  value: /
            timeouts:
              request:  "180s"

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 150Mi
        globalMounts:
          - path: /config
      data:
        enabled: true
        type: nfs
        server: "nas.home.arpa"
        path: "/srv/nfs4/data"
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
