kind: VMProbe
apiVersion: operator.victoriametrics.com/v1beta1
metadata:
  name: radarr
  namespace: homelab
spec:
  interval: "30s"
  module: http_2xx
  jobName: radarr
  vmProberSpec:
    url: blackbox-exporter.observability.svc.cluster.local:9115
    path: /probe
    scheme: http
  targets:
    staticConfig:
      targets:
        - http://radarr.homelab.svc.cluster.local:7878
      labels:
        name: Radarr
        category: Arr Suite

