name: Render manifests to OCI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: jdx/mise-action@v4
        with:
          install: true

      - name: Login to GHCR
        run: echo "${GITHUB_TOKEN}" | flux registry login ghcr.io --username "${GITHUB_ACTOR}" --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render manifests
        run: |
          mkdir -p rendered
          cd test
          pkl eval deployment.pkl > ../rendered/deployment.yaml

      - name: Push rendered manifests
        run: |
          flux push artifact oci://ghcr.io/${{ github.repository_owner }}/oracle-ops-backstage-dev:main \
            --path=./rendered \
            --source="${{ github.server_url }}/${{ github.repository }}" \
            --revision="${{ github.ref_name }}@sha1:${{ github.sha }}" \
            --annotations='org.opencontainers.image.source=https://github.com/${{ github.repository }}'
